import Head from 'next/head'
import { useEffect, useState } from 'react';
import axios from 'axios';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [status, setStatus] = useState(2);
  const [submitError, setSubmitError] = useState(null);
  const [numberValue, setNumberValue] = useState();

  const submitForm = () => {
    if(!numberValue || numberValue < 1) {
      setSubmitError('Number must be greater than 0');
      return;
    }

    setSubmitError(null);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Fena Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.description}>
          <input className={styles.numberInput}
            type={"number"} min="0"
            onInput={(e) => setNumberValue(e.target.value)} 
          />
          { submitError ?
            <span className={styles.errorSpan}>{submitError}</span>
          : null
          }
          <button className={styles.submitBtn} onClick={submitForm}>
            Submit
          </button>

          { status ?
            <div className={styles.statusBlock}>
              <span>{status} out of {numberValue}</span>
            </div>
          : null
          }
        </div>
        
      </main>

    </div>
  )
}
